import { StyleSheet } from "react-native";
/**
 * 会话详情页样式表（从页面组件外移，主题色经 createStyles 注入）。
 */
import type { ThemeColors } from "@/ui/theme";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    page: { flex: 1, backgroundColor: colors.canvas },
    keyboardArea: { flex: 1 },
    timelineArea: { flex: 1, position: "relative" },
    header: {
      backgroundColor: colors.canvas,
      minHeight: 56,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 13,
    },
    headerControlPressed: { opacity: 0.55 },
    headerText: { flex: 1 },
    name: { color: colors.ink, fontSize: 17, fontWeight: "600" },
    company: { color: colors.muted, fontSize: 13, marginTop: 2 },
    headerStatus: { color: colors.blue, fontSize: 12, fontWeight: "500" },
    moreButton: {
      width: 34,
      height: 34,
      alignItems: "center",
      justifyContent: "center",
    },
    chat: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 28 },
    timelineHeader: { gap: 10, marginBottom: 12 },
    archivedDraftPanel: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.rule,
      backgroundColor: colors.paper,
    },
    archivedDraftTitle: { color: colors.ink, fontSize: 12, fontWeight: "700" },
    archivedDraftHint: { color: colors.muted, fontSize: 10, marginTop: 3 },
    archivedDraftText: {
      color: colors.ink,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 8,
    },
    archivedDraftAction: {
      color: colors.blue,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 9,
    },
    timelineItem: { marginBottom: 12 },
    offlineBanner: {
      backgroundColor: colors.orangeWash,
      borderRadius: 14,
      padding: 13,
    },
    offlineTitle: { color: colors.navy, fontSize: 12, fontWeight: "800" },
    grabber: {
      width: 34,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.rule,
      alignSelf: "center",
      marginBottom: 16,
    },
    eventDotActive: {
      width: 5,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.blue,
    },
    eventText: { color: colors.muted, fontSize: 10 },
    collaborationPanel: {
      backgroundColor: colors.paper,
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 15,
      padding: 14,
      gap: 10,
      marginHorizontal: 16,
      marginTop: 8,
      shadowColor: colors.shadow,
      shadowOpacity: 0.12,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 3,
    },
    collaborationLabel: {
      color: colors.navy,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.8,
    },
    collaborationRow: {
      borderTopWidth: 1,
      borderColor: colors.rule,
      paddingTop: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    collaborationRowPressed: { opacity: 0.55 },
    collaborationHint: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "700",
      paddingHorizontal: 6,
      paddingVertical: 4,
    },
    collaborationCopy: { flex: 1 },
    collaborationTitle: { color: colors.ink, fontSize: 12, fontWeight: "800" },
    collaborationStatus: { color: colors.muted, fontSize: 11, marginTop: 3 },
    collaborationReason: {
      color: colors.muted,
      fontSize: 11,
      lineHeight: 16,
      marginTop: 5,
    },
    collaborationButton: {
      backgroundColor: colors.orange,
      borderRadius: 12,
      paddingHorizontal: 13,
      paddingVertical: 8,
    },
    collaborationButtonText: {
      color: colors.onPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    collaborationSecondaryButton: {
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 16,
      paddingHorizontal: 13,
      paddingVertical: 8,
    },
    collaborationSecondaryText: {
      color: colors.navy,
      fontSize: 11,
      fontWeight: "800",
    },
    modalHint: {
      color: colors.muted,
      fontSize: 11,
      lineHeight: 16,
      marginTop: 6,
    },
    responseInput: {
      minHeight: 120,
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 12,
      marginTop: 14,
      padding: 12,
      color: colors.ink,
      textAlignVertical: "top",
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 9,
      marginTop: 13,
    },
    modalCancel: { paddingHorizontal: 14, paddingVertical: 10 },
    modalCancelText: { color: colors.muted, fontWeight: "800", fontSize: 12 },
    modalConfirm: {
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
    },
    modalConfirmText: { color: colors.onPrimary, fontWeight: "800", fontSize: 12 },
    composerDock: { backgroundColor: colors.paper },
    bottomDock: { backgroundColor: colors.paper },
    composerMeta: {
      minHeight: 24,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 9,
      paddingHorizontal: 4,
    },
    offlineDraft: {
      color: colors.muted,
      fontSize: 11,
      paddingHorizontal: 4,
      paddingBottom: 2,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.32)",
      justifyContent: "flex-end",
    },
    modalDismiss: { flex: 1 },
    briefingHeadline: {
      color: colors.ink,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 15,
    },
    menuDismiss: { flex: 1 },
    menuSheet: {
      maxHeight: "72%",
      backgroundColor: colors.paper,
      paddingHorizontal: 18,
      paddingTop: 9,
      paddingBottom: 30,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    menuActionRow: {
      minHeight: 46,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 4,
    },
    menuActionRowPressed: { opacity: 0.65 },
    menuActionRowDisabled: { opacity: 0.4 },
    menuActionText: { color: colors.blue, fontSize: 14, fontWeight: "600" },
    menuActionHint: { color: colors.muted, fontSize: 11, marginTop: -3 },
    menuSectionLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 0.9,
      marginTop: 22,
      marginBottom: 12,
    },
    menuCollabRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: colors.rule,
    },
    menuCollabCopy: { flex: 1 },
    menuCollabTitle: { color: colors.ink, fontSize: 13, fontWeight: "700" },
    menuCollabStatus: { color: colors.muted, fontSize: 11, marginTop: 3 },
    menuCollabAction: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.rule,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    menuCollabActionDanger: {
      borderColor: colors.red,
      backgroundColor: colors.redWash,
    },
    menuCollabActionPressed: { opacity: 0.6 },
    menuCollabActionText: {
      color: colors.ink,
      fontSize: 11,
      fontWeight: "800",
    },
    menuCollabActionTextDanger: { color: colors.red },
    contactCardPressed: { opacity: 0.68 },
    contactAvatar: {
      width: 38,
      height: 38,
      borderRadius: 13,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    contactAvatarText: { color: colors.onPrimary, fontSize: 14, fontWeight: "800" },
    contactCopy: { flex: 1 },
    contactName: { color: colors.ink, fontSize: 14, fontWeight: "800" },
    contactCompany: { color: colors.muted, fontSize: 10, marginTop: 3 },
    profileBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.32)",
      justifyContent: "flex-end",
    },
    profileSheet: {
      height: "82%",
      backgroundColor: colors.paper,
      paddingHorizontal: 18,
      paddingTop: 9,
      paddingBottom: 28,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    profileHeadingCopy: { flex: 1, paddingRight: 18 },
    profileLoading: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    profileLoadingText: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: "700",
    },
    profileRetry: {
      color: colors.blue,
      fontSize: 11,
      fontWeight: "800",
      marginTop: 8,
    },
    profileIdentity: {
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
      borderRadius: 15,
      backgroundColor: colors.canvas,
      padding: 13,
      marginTop: 18,
      marginBottom: 21,
    },
    profileLabel: {
      color: colors.ink,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 18,
      marginBottom: 7,
    },
    profileNoteInput: {
      minHeight: 104,
      maxHeight: 160,
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 14,
      backgroundColor: colors.paper,
      color: colors.ink,
      fontSize: 14,
      lineHeight: 20,
      padding: 12,
      textAlignVertical: "top",
    },
    profileCounter: {
      color: colors.muted,
      fontSize: 9,
      textAlign: "right",
      marginTop: 5,
      marginBottom: 18,
    },
    profileTagsInput: {
      minHeight: 46,
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 13,
      color: colors.ink,
      fontSize: 14,
      paddingHorizontal: 12,
    },
    profileHint: { color: colors.muted, fontSize: 9, marginTop: 6 },
    profileError: {
      color: colors.red,
      fontSize: 10,
      fontWeight: "700",
      marginTop: 12,
    },
    profileSaved: {
      color: colors.green,
      fontSize: 10,
      fontWeight: "800",
      marginTop: 12,
    },
    profileSave: {
      minHeight: 48,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 18,
      marginBottom: 12,
    },
    profileSaveDisabled: { opacity: 0.4 },
    profileSavePressed: { transform: [{ scale: 0.992 }], opacity: 0.84 },
    profileSaveText: { color: colors.onPrimary, fontSize: 13, fontWeight: "800" },
    menuEmpty: {
      borderRadius: 14,
      backgroundColor: colors.canvas,
      padding: 16,
    },
    menuEmptyTitle: { color: colors.ink, fontSize: 13, fontWeight: "800" },
    menuEmptyText: { color: colors.muted, fontSize: 11, marginTop: 4 },
    menuHistoryRow: {
      minHeight: 46,
      justifyContent: "center",
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.rule,
    },
    menuHistoryText: { color: colors.blue, fontSize: 13, fontWeight: "600" },
    responseSheet: {
      backgroundColor: colors.paper,
      padding: 18,
      paddingBottom: 28,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    modalGrabber: {
      alignSelf: "center",
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.rule,
      marginBottom: 3,
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
    },
    modalTitle: { color: colors.ink, fontSize: 20, fontWeight: "800" },
    modalSub: { color: colors.muted, fontSize: 11, marginTop: 4 },
    modalClose: { color: colors.navy, fontSize: 12, fontWeight: "800" },
    reasonInput: {
      minHeight: 45,
      borderWidth: 1,
      borderColor: colors.rule,
      borderRadius: 11,
      paddingHorizontal: 11,
      color: colors.ink,
    },
    queueText: { flex: 1, gap: 3 },
    queueName: { color: colors.ink, fontSize: 14, fontWeight: "800" },
    queueDescription: { color: colors.muted, fontSize: 11 },
    assigneeAvatarText: { color: colors.ink, fontSize: 13, fontWeight: "800" },
    assigneeEmpty: {
      color: colors.muted,
      fontSize: 12,
      paddingVertical: 18,
      textAlign: "center",
    },
    loadOlder: {
      minHeight: 38,
      alignSelf: "center",
      borderRadius: 12,
      backgroundColor: colors.paper,
      paddingHorizontal: 13,
      alignItems: "center",
      justifyContent: "center",
      marginVertical: 3,
    },
    loadOlderPressed: { opacity: 0.65 },
    loadOlderContent: { flexDirection: "row", alignItems: "center", gap: 5 },
    loadOlderText: { color: colors.blue, fontSize: 10, fontWeight: "800" },
    olderError: {
      alignSelf: "center",
      paddingVertical: 7,
      paddingHorizontal: 10,
    },
    olderErrorText: { color: colors.orange, fontSize: 10, fontWeight: "700" },
    newMessages: {
      position: "absolute",
      alignSelf: "center",
      bottom: 12,
      minHeight: 38,
      borderRadius: 19,
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      shadowColor: colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 13,
      shadowOffset: { width: 0, height: 5 },
      elevation: 4,
    },
    newMessagesPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
    newMessageDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: "colors.primary",
    },
    newMessagesText: { color: colors.onPrimary, fontSize: 11, fontWeight: "800" },
    date: {
      alignSelf: "center",
      color: colors.muted,
      fontSize: 10,
      fontWeight: "700",
      backgroundColor: colors.paper,
      borderRadius: 10,
      paddingHorizontal: 9,
      paddingVertical: 4,
      marginVertical: 5,
    },
    systemEvent: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
      marginVertical: 5,
    },
    systemLine: { flex: 1, height: 1, backgroundColor: colors.rule },
    // 拍一拍：居中灰字提示，弱于聊天气泡
    patNotice: { alignItems: "center", marginVertical: 5 },
    patNoticeText: { color: colors.muted, fontSize: 11 },
    system: {
      alignSelf: "center",
      color: colors.muted,
      fontSize: 10,
      marginVertical: 2,
    },
    messageRow: { flexDirection: "row", alignItems: "flex-end", gap: 7 },
    left: { justifyContent: "flex-start" },
    right: { justifyContent: "flex-end" },
    bubble: {
      borderRadius: 17,
      paddingHorizontal: 13,
      paddingVertical: 10,
      maxWidth: "76%",
    },
    // 媒体裸渲染（微信式）：图片/文件/表情不带聊天气泡底
    bubbleBare: {
      paddingHorizontal: 0,
      paddingVertical: 0,
      backgroundColor: "transparent",
      borderWidth: 0,
      borderRadius: 10,
      overflow: "visible" as const,
    },
    customer: {
      backgroundColor: colors.paper,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.rule,
      borderTopLeftRadius: 5,
    },
    agent: { backgroundColor: colors.blueWash, borderTopRightRadius: 5 },
    me: { backgroundColor: colors.primary, borderTopRightRadius: 5 },
    messageAvatar: {
      width: 27,
      height: 27,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 1,
      overflow: "hidden",
    },
    messageAvatarImage: { width: 27, height: 27, borderRadius: 9 },
    messageAvatarCustomer: {
      backgroundColor: colors.paper,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.rule,
    },
    messageAvatarAgent: { backgroundColor: colors.blueWash },
    messageAvatarManual: { backgroundColor: colors.ink },
    messageAvatarText: { color: colors.paper, fontSize: 10, fontWeight: "700" },
    messageAvatarAgentText: { color: colors.blue, fontSize: 10, fontWeight: "800" },
    messageText: { color: colors.ink, fontSize: 14, lineHeight: 20 },
    messageImagePressed: { opacity: 0.82 },
    imageLoading: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.canvas,
    },
    imageHint: {
      position: "absolute",
      right: 7,
      bottom: 7,
      borderRadius: 9,
      backgroundColor: "rgba(18,57,68,0.84)",
      paddingHorizontal: 7,
      paddingVertical: 4,
    },
    imageHintText: { color: "white", fontSize: 10, fontWeight: "800" },
    imageFailure: {
      width: 220,
      minHeight: 116,
      borderRadius: 11,
      backgroundColor: colors.orangeWash,
      alignItems: "center",
      justifyContent: "center",
      padding: 14,
    },
    imageFailureAction: {
      color: colors.orange,
      fontSize: 9,
      fontWeight: "800",
      marginTop: 4,
    },
    meText: { color: colors.onPrimary },
    // 引用回复卡片
    quoteCard: {
      marginBottom: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderLeftWidth: 2,
      borderLeftColor: colors.muted,
      backgroundColor: colors.subtle,
      borderRadius: 4,
    },
    quoteAuthor: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.muted,
    },
    quoteText: {
      fontSize: 11,
      color: colors.muted,
    },
    // @提及高亮
    mentionText: { color: colors.primary, fontWeight: "600" },
    mentionTextOnDark: { color: "rgba(255,255,255,0.92)" },
    messageTime: {
      color: colors.muted,
      fontSize: 10,
      marginTop: 6,
      alignSelf: "flex-end",
    },
    messageTimeOnDark: { color: "rgba(255,255,255,0.78)" },
    // 初始加载：静态气泡形骨架（无动画，Motion 2 原则）
    skeletonList: { paddingVertical: 12, gap: 14 },
    skeletonRow: { alignItems: "flex-start" },
    skeletonRowOutbound: { alignItems: "flex-end" },
    skeletonBubble: {
      width: "68%",
      height: 44,
      borderRadius: 17,
      backgroundColor: colors.subtle,
    },
    loadError: { paddingVertical: 24, alignItems: "center", gap: 10 },
    loadErrorAction: {
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: colors.subtle,
    },
    loadErrorActionPressed: { opacity: 0.8 },
    loadErrorActionText: { color: colors.blue, fontSize: 13, fontWeight: "700" },
    pending: { color: "rgba(255,255,255,0.78)", fontSize: 10, marginTop: 7 },
    pendingOnBare: { color: colors.muted },
    composer: {
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 8,
      backgroundColor: colors.paper,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: colors.rule,
      gap: 8,
    },
    characterCount: { color: colors.muted, fontSize: 10 },
    toolButtonPressed: { opacity: 0.6 },
    inputRow: {
      minHeight: 48,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      borderRadius: 17,
      backgroundColor: colors.canvas,
      padding: 4,
    },
    input: {
      flex: 1,
      minHeight: 40,
      maxHeight: 112,
      paddingHorizontal: 4,
      paddingVertical: 0,
      color: colors.ink,
      // 单行：文字垂直居中，与 +/发送按钮对齐
      textAlignVertical: "center",
    },
    inputMultiline: {
      // 多行：顶对齐，避免文本块悬浮居中
      textAlignVertical: "top",
      paddingTop: 11,
      paddingBottom: 9,
    },
    send: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary,
      borderRadius: 12,
    },
    plusButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    sendDisabled: { opacity: 0.5 },
    sendPressed: { opacity: 0.8 },
    moreActions: {
      borderRadius: 15,
      backgroundColor: colors.canvas,
      padding: 6,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 4,
    },
    moreActionButton: {
      width: "48%",
      minHeight: 62,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    moreActionTitle: { color: colors.ink, fontSize: 10.5, fontWeight: "600" },
    panel: {
      backgroundColor: colors.paper,
      borderTopWidth: 1,
      borderColor: colors.rule,
      padding: 14,
      gap: 10,
    },
    panelTitle: { color: colors.muted, fontSize: 12, textAlign: "center" },
    panelDetails: { gap: 7, paddingVertical: 2 },
    panelDetailRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
    panelDetailDot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      marginTop: 6,
      backgroundColor: colors.blue,
    },
    panelDetailText: {
      flex: 1,
      color: colors.ink,
      fontSize: 11,
      lineHeight: 17,
    },
    panelButton: { flex: 1, padding: 14, borderRadius: 12, alignItems: "center" },
    panelButtonPressed: { opacity: 0.8 },
    panelButtonText: { fontSize: 14, fontWeight: "800" },
    panelActions: { flexDirection: "row", gap: 10, marginTop: 12 },
    panelButtonSecondary: { flex: 1, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.rule },
    panelButtonSecondaryText: { color: colors.blue, fontSize: 14, fontWeight: "700" },
    draftWarning: { color: colors.orange, fontSize: 10, fontWeight: "700" },
    draftStale: { gap: 4 },
    draftReview: { color: colors.navy, fontSize: 10, fontWeight: "800" },
    // 引用回复预览条
    replyPreview: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.canvas,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginBottom: 4,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
    },
    replyPreviewContent: { flex: 1, gap: 1 },
    replyPreviewLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: "700",
    },
    replyPreviewText: {
      color: colors.ink,
      fontSize: 12,
    },
    // 消息长按操作菜单
    messageMenuBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.32)",
      justifyContent: "flex-end",
    },
    messageMenuSheet: {
      backgroundColor: colors.paper,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 28,
      gap: 4,
    },
    messageMenuTitle: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: "600",
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    messageMenuAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderRadius: 10,
    },
    messageMenuActionText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: "600",
    },
  });

