#!/usr/bin/env node
/**
 * Channel 协议同步：从 @weflow/contracts 的 CHANNEL_PROTOCOL 生成
 * Channel Host 侧 channel_protocol.py（跨语言对齐的单一权威传导）。
 *
 * 用法（weflow 仓库根）：
 *   node core/node_modules/tsx/dist/cli.mjs scripts/sync-channel-protocol.mjs          # 生成
 *   node core/node_modules/tsx/dist/cli.mjs scripts/sync-channel-protocol.mjs --check  # 校验（CI）
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CHANNEL_PROTOCOL } from "../packages/contracts/src/channel.ts";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const HOST_PACKAGE_DIR = join(ROOT, "runtimes", "channel-host-wechat", "channel_host");
const OUTPUT = join(HOST_PACKAGE_DIR, "channel_protocol.py");

function renderPython(protocol: typeof CHANNEL_PROTOCOL): string {
  const quote = (items: readonly string[]): string =>
    `(${items.map((item) => `"${item}"`).join(", ")})`;
  return [
    '"""Generated by weflow/scripts/sync-channel-protocol.mjs — DO NOT EDIT.',
    "Single source of truth: packages/contracts/src/channel.ts (CHANNEL_PROTOCOL).",
    '"""',
    "",
    `PROTOCOL_VERSION = ${protocol.protocolVersion}`,
    "",
    `SEND_OPERATION_STATES = ${quote(protocol.sendOperationStates)}`,
    `SEND_KINDS = ${quote(protocol.sendKinds)}`,
    `MEDIA_STATES = ${quote(protocol.mediaStates)}`,
    `ERROR_CODES = ${quote(protocol.errorCodes)}`,
    "",
    "",
  ].join("\n");
}

const generated = renderPython(CHANNEL_PROTOCOL);
const checkMode = process.argv.includes("--check");

if (checkMode) {
  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    // 文件缺失 → 视为不一致
  }
  if (current.trim() !== generated.trim()) {
    console.error(`[sync-channel-protocol] MISMATCH: ${OUTPUT} is stale`);
    console.error("run: node core/node_modules/tsx/dist/cli.mjs scripts/sync-channel-protocol.mjs");
    process.exit(1);
  }
  console.log("[sync-channel-protocol] OK: host protocol file is in sync");
  process.exit(0);
}

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, generated, "utf8");
console.log(`[sync-channel-protocol] wrote ${OUTPUT}`);
