"""Generated by weflow/scripts/sync-channel-protocol.mjs — DO NOT EDIT.
Single source of truth: packages/contracts/src/channel.ts (CHANNEL_PROTOCOL).
"""

PROTOCOL_VERSION = 4

SEND_OPERATION_STATES = ("pending", "executing", "confirmed", "unknown", "failed")
SEND_KINDS = ("text", "file", "image", "reply", "mention", "poke", "recall", "voice")
MEDIA_STATES = ("ready", "pending", "not_found", "failed")
ERROR_CODES = ("send_operation_identity_conflict", "media_pending", "media_not_found", "not_found", "channel_contacts_unavailable", "invalid_request", "channel_host_error", "wechat_send_not_confirmed", "at_requires_at_least_one_member", "recall_window_expired", "recall_not_found", "recall_unsupported", "video_not_found", "voice_path_invalid", "reply_target_not_latest", "mention_member_not_found")
